#!/bin/bash
# /etc/init.d/gophish
# Description: Initialization file: service gophish {start|stop|status} 
# Config:/opt/gophish/config.json

processName=Gophish
process=gophish
appDirectory=/opt/gophish
logfile=/var/log/gophish/gophish.log
errfile=/var/log/gophish/gophish.error

start() 
{
echo 'Starting '${processName}'...'
cd ${appDirectory}
nohup ./$process >>$logfile 2>>$errfile &
sleep 1
}

stop() 
{
echo 'Stopping '${processName}'...'
pid=$(/usr/bin/pidof ${process})
kill ${pid}
sleep 1
}

status() 
{
pid=$(/usr/bin/pidof ${process})
if [[ "$pid" != "" ]]; then
echo ${processName}' is running...'
else
echo ${processName}' is not running...'
fi
}

case $1 in
start|stop|status) "$1" ;;
esac
